/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#4edea3",
        "secondary-fixed": "#6ffbbe",
        "on-surface-variant": "#c2c6d6",
        "error": "#ffb4ab",
        "surface-variant": "#27354c",
        "error-container": "#93000a",
        "inverse-on-surface": "#233148",
        "inverse-surface": "#d6e3ff",
        "surface-container-high": "#1c2a41",
        "on-error": "#690005",
        "primary-container": "#4d8eff",
        "primary-fixed": "#d8e2ff",
        "on-secondary-fixed": "#002113",
        "on-tertiary": "#68000a",
        "surface-bright": "#2c3951",
        "on-tertiary-fixed": "#410004",
        "surface-container-low": "#0d1c32",
        "inverse-primary": "#005ac2",
        "on-tertiary-fixed-variant": "#930013",
        "outline-variant": "#424754",
        "tertiary-fixed-dim": "#ffb3ad",
        "primary-fixed-dim": "#adc6ff",
        "background": "#041329",
        "tertiary-container": "#ff5451",
        "on-surface": "#d6e3ff",
        "on-primary": "#002e6a",
        "primary": "#adc6ff",
        "surface": "#041329",
        "surface-container-lowest": "#010e24",
        "secondary": "#4edea3",
        "on-secondary-container": "#00311f",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005236",
        "secondary-container": "#00a572",
        "surface-container-highest": "#27354c",
        "on-primary-fixed-variant": "#004395",
        "on-primary-container": "#00285d",
        "surface-container": "#112036",
        "surface-tint": "#adc6ff",
        "on-secondary": "#003824",
        "on-primary-fixed": "#001a42",
        "tertiary": "#ffb3ad",
        "outline": "#8c909f",
        "surface-dim": "#041329",
        "on-background": "#d6e3ff",
        "on-tertiary-container": "#5c0008",
        "tertiary-fixed": "#ffdad7"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontSize: {
        "body-sm": ["13px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "label-caps": ["11px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "title-sm": ["18px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "data-mono": ["13px", {"lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "display-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      },
      spacing: {
          'gutter': '1.5rem',
      }
    },
  },
  plugins: [],
}
