apiVersion: v1
kind: Service
metadata:
  name: ascend-api-service
spec:
  selector:
    app: ascend-api
    # In production, point this to blue or green as needed
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
